name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.23.7"

      - name: build
        run: |
          mkdir dist
          go build -o dist/sqldot

      - name: upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: dist

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
